#!/bin/bash

quiet=

name=`hostname`
export RESTIC_PASSWORD_FILE=~/.resticpw
include=restic-backup-include.conf
exclude=restic-backup-exclude.conf
if test -f /etc/$include; then
 	include=/etc/$include
 	exclude=/etc/$exclude;
else
 	include=.$include
 	exclude=.$exclude;
fi
if ! test -f $include; then
	/usr/bin/logger "$include not found"
	exit 1;
fi
case "$1" in
    "lan")
	export RESTIC_REPOSITORY="sftp:"`whoami`"@raspberrypi2:Backup/$name"
	
    ;;
    "onedrive")
	export RESTIC_REPOSITORY="rclone:onedrive:backup/$name"
    ;;
    *)
	echo "usage: $0 lan|onedrive tag"
	exit 1
	;;
esac

/usr/bin/logger "$0: backup (restic) of $name to $RESTIC_REPOSITORY started."

# Backup
restic backup $quiet --tag $2 --files-from $include --exclude-file $exclude --exclude $RESTIC_PASSWORD_FILE

#Check
restic check

/usr/bin/logger "$0: finished."
exit 0
