#!/bin/bash

logfile=/var/log/restic-backup.log
errfile=/var/log/restic-backup.err

# Check for root user
checkroot()
{
    # Check for root user
    if [ `whoami` != "root" ]; then
	echo "$0 must be run as root" 1>&2
	exit 1
    fi
}


# Define path to restic executable
if [ `uname` == "Darwin" ]; then
	prog=/opt/local/bin/restic
else
	prog=/usr/bin/restic
fi

# Check for verbose output: default no
if [ "$verbose" == "yes" ]; then
    verbose="--verbose=3"
else
    verbose=
fi

# Check for quiet execution of restic: default yes
if [ "$quiet" != "no" ]; then
    quiet=--quiet
else
    quiet=
fi

export RESTIC_PASSWORD_FILE=~/.resticpw

help()
{
    echo "usage: $0 lan|onedrive|help"
    echo
    echo "VARIABLES:"
    echo "quiet  verbose  output"
    echo "--------------------------------"
    echo "yes    --       no std out"
    echo "no     no       normal std out"
    echo "no     yes      extended std out"
}

log()
{
    echo `date`": $1" >> $logfile
}

# Calculate repository
case "$1" in
    "lan")
	export RESTIC_REPOSITORY="sftp:"`whoami`"@raspberrypi2:/var/Backup/hebbie"
	;;
    "onedrive")
	export RESTIC_REPOSITORY="rclone:onedrive:backup/hebbie"
	;;
    "help")
	help
	exit 0
	;;
    *)
	help
	exit 1
	;;
esac      

# Do the job
checkroot
log "$0: check (restic) of $RESTIC_REPOSITORY started."

log "   Checking $RESTIC_REPOSITORY ..."

$prog unlock
{ err="$( { $prog check $quiet $verbose; } 2>&1 1>&3 3<&- )"; } 3>&1
if [ $? -ne 0 ]; then
    echo $err
    log "   $err"
    log "$0: check (restic) of $RESTIC_REPOSITORY failed."
    exit 1
fi

log "$0: check (restic) of $RESTIC_REPOSITORY finished."

exit 0
