#!/bin/bash

if [ `whoami` != "root" ]; then
    echo "$0 must be run as root"
    exit 1
fi

quiet=""

name=`hostname`
export RESTIC_PASSWORD_FILE=~/.resticpw
source=/root/Backup/$1
destination=onedrive:backup/$1

/usr/bin/logger "$0: cloning (rclone) of $source to $destination started."

echo "Sync (rclone) $source with $destination ..."
rclone sync -P $quiet $source $destination

/usr/bin/logger "$0: cloning (rclone) of $source to $destionation finished."
exit 0
