#!/bin/bash

if [ `uname` == "Darwin" ]; then
	prog=/opt/local/bin/restic
else
	prog=/usr/bin/restic
fi

RESTIC_PASSWORD_FILE=~/.resticpw
export RESTIC_PASSWORD_FILE

case "$1" in
	"lan")
		RESTIC_REPOSITORY=sftp:`whoami`@raspberrypi2:Backup/`hostname`
		export RESTIC_REPOSITORY
	;;
	"onedrive")
		RESTIC_REPOSITORY=rclone:onedrive:backup/`hostname`
		export RESTIC_REPOSITORY
	;;
	*)
		echo "usage: $0 lan | onecrive"
	;;
esac
$prog --quiet generate --bash-completion ~/.bash_completion
source ~/.bash_completion
