#!/bin/bash
NAME=`hostname`
export RESTIC_PASSWORD_FILE=~/.resticpw
BACKUP_CMD=restic
BACKUP_SUBCMD=backup
BACKUP_INCLUDE=restic-backup-include.conf
BACKUP_EXCLUDE=restic-backup-exclude.conf
if test -f /etc/${BACKUP_INCLUDE}; then
 	BACKUP_INCLUDE=/etc/${BACKUP_INCLUDE}
 	BACKUP_EXCLUDE=/etc/${BACKUP_EXCLUDE};
else
 	BACKUP_INCLUDE=.${BACKUP_INCLUDE}
 	BACKUP_EXCLUDE=.${BACKUP_EXCLUDE};
fi
if ! test -f ${BACKUP_INCLUDE}; then
	/usr/bin/logger "${BACKUP_INCLUDE} not found"
	exit 1;
fi
BACKUP_TAGS="--tag $2"
BACKUP_QUIET=
case "$1" in
    "lan")
	export RESTIC_REPOSITORY="sftp:"`whoami`"@raspberrypi2:Backup/${NAME}"
	
    ;;
    "onedrive")
	export RESTIC_REPOSITORY="rclone:onedrive:backup/${NAME}"
    ;;
    *)
	echo "usage: ${BACKUP_CMD} lan|onedrive tag"
	exit 1
	;;
esac
/usr/bin/logger "$0: backup (restic) of ${NAME} to ${RESTIC_REPOSITORY} started."
echo ${BACKUP_CMD} ${BACKUP_SUBCMD} ${BACKUP_QUIET} ${BACKUP_TAGS} --files-from ${BACKUP_INCLUDE} --exclude-file ${BACKUP_EXCLUDE} --exclude ${RESTIC_PASSWORD_FILE}
${BACKUP_CMD} ${BACKUP_SUBCMD} ${BACKUP_QUIET} ${BACKUP_TAGS} --files-from ${BACKUP_INCLUDE} --exclude-file ${BACKUP_EXCLUDE} --exclude ${RESTIC_PASSWORD_FILE}
/usr/bin/logger "$0: backup (restic) of ${NAME} to ${RESTIC_REPOSITORY} finished."
exit 0
