#!/bin/bash

logfile=/var/log/restic-backup.log
errfile=/var/log/restic-backup.err

# Check for root user
checkroot()
{
    # Check for root user
    if [ `whoami` != "root" ]; then
	echo "$0 must be run as root" 1>&2
	exit 1
    fi
}

# Define path to restic executable
if [ `uname` == "Darwin" ]; then
	prog=/opt/local/bin/restic
else
	prog=/usr/bin/restic
fi
verbose="no"
quiet="yes"
dryrun="no"

# Command line options - see below in function help for details.
while getopts vpd flag
do
    case "${flag}" in
	v) verbose="yes";;
	p) quiet="no";;
	d) dryrun="yes";;
    esac
done
# adjust argument index to point to non-option arguments:
# $1 and $2 will point to them
shift $((OPTIND - 1))

# Check for verbose output: default no
if [ "$verbose" == "yes" ]; then
    verbose="--verbose=2"
else
    verbose=
fi

# Check for quiet execution of restic: default yes
if [ "$quiet" != "no" ]; then
    quiet=--quiet
    verbose=
else
    quiet=
fi


name=$2

export RESTIC_PASSWORD_FILE=~/.resticpw

help()
{
    echo "Print list of snapshots for given location and host."
    echo
    echo "usage: $0 OPTIONS LOCATION HOST"
    echo "OPTIONS:"
    echo "  -n	Do not check the respository after completion."
    echo "  -p	Show progress."
    echo "  -v	Be verbose."
    echo "  -d	Dry-run."
    echo
    echo "LOCATION:"
    echo "  lan       Backup to repo on local SFTP server."
    echo "  onedrive  Backup to repo on ONEDRIVE server."
    echo "  local     Backup to local repo."
    echo "  help      Print this help."
    echo
    echo "HOST:"
    echo "  all       List snapshots for all hosts."
    echo "  <host>    List snapshots only for given <host>."
}

# We may check any hosts repository
if [ "$name" = "" ]; then
    name=`hostname`
fi

case "$1" in
    "lan")
    	export RESTIC_REPOSITORY="sftp:"`whoami`"@raspberrypi2:/var/Backup/hebbie"
    ;;
    "onedrive")
	export RESTIC_REPOSITORY="rclone:onedrive:backup/hebbie"
	;;
    "local")
	export RESTIC_REPOSITORY="/Volumes/BackupDisk/hebbie"
	;;
    "help")
	help
	exit 0
	;;
    *)
	help
	exit 1
	;;
esac

checkroot

echo "repository: $RESTIC_REPOSITORY"
$prog unlock

if [ "$name" = "all" ]; then
#    $prog snapshots  --compact $quiet $verbose
    $prog snapshots  $quiet $verbose
else
    $prog snapshots -H $name --compact $quiet $verbose
fi
exit 0
