#!/bin/bash

logfile=/var/log/restic-backup.log
errfile=/var/log/restic-backup.err

# Check for root user
if [ `whoami` != "root" ]; then
    echo "$0 must be run as root" 1>&2
    exit 1
fi

# Define path to restic executable
if [ `uname` == "Darwin" ]; then
	prog=/opt/local/bin/restic
else
	prog=/usr/bin/restic
fi

# Check for verbose output: default no

if [ "$verbose" == "yes" ]; then
    verbose="--verbose=3"
else
    verbose=
fi

# Check for quiet execution of restic: default yes
if [ "$quiet" != "no" ]; then
    quiet=--quiet
    verbose=
else
    quiet=
fi

name=$2
export RESTIC_PASSWORD_FILE=~/.resticpw

help()
{
    echo "usage: $0 lan|onedrive [hostname|all]"
    echo
    echo "quiet  verbose  output"
    echo "--------------------------------"
    echo "yes    --       no std out"
    echo "no     no       normal std out"
    echo "no     yes      extended std out"
}

# We may check any hosts repository
if [ "$name" = "" ]; then
    name=`hostname`
fi

case "$1" in
    "lan")
    	export RESTIC_REPOSITORY="sftp:"`whoami`"@raspberrypi2:/var/Backup/hebbie"
    ;;
    "onedrive")
	export RESTIC_REPOSITORY="rclone:onedrive:backup/hebbie"
	;;
    "help")
	help
	exit 0
	;;
    *)
	help
	exit 1
	;;
esac

echo "repository: $RESTIC_REPOSITORY"
$prog unlock

if [ "$name" = "all" ]; then
    $prog snapshots  --compact $quiet $verbose
else
    $prog snapshots -H $name --compact $quiet $verbose
fi
exit 0
