#!/bin/bash

quiet=

name=$2
export RESTIC_PASSWORD_FILE=~/.resticpw

if [ "$name" = "" ]; then
    name=`hostname`
fi

case "$1" in
    "lan")
	export RESTIC_REPOSITORY="sftp:"`whoami`"@raspberrypi2:Backup/$name"
	
    ;;
    "onedrive")
	export RESTIC_REPOSITORY="rclone:onedrive:backup/$name"
    ;;
    *)
	echo "usage: $0 lan|onedrive hostname"
	exit 1
	;;
esac
echo "repository: $RESTIC_REPOSITORY"
restic snapshots --compact
exit 0
