#!/bin/bash

logfile=/var/log/restic-backup.log
errfile=/var/log/restic-backup.err

# Check for root user
if [ `whoami` != "root" ]; then
    echo "$0 must be run as root"
    exit 1
fi

if [ "$quiet" != "no" ]; then
    quiet=--quiet
else
    quiet=
fi

quiet=""


export RESTIC_PASSWORD_FILE=~/.resticpw

help()
{
    echo "usage: restic-clone host"
    echo "quiet=no ==> don't be quiet."
}

log()
{
    echo `date`": $1" >> $logfile
}

case "$1" in
    "help")
	help
	exit 0
	;;
esac

source=$HOME/Backup/$1
destination=onedrive:backup/$1

log "$0: cloning (rclone) of $source to $destination started."

log "   Sync (rclone) $source with $destination ..."
rclone sync -P $quiet $source $destination

log "$0: cloning (rclone) of $source to $destionation finished."
exit 0
